# Generated by Django 4.0 on 2022-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Division', models.CharField(max_length=50)),
            ],
        ),
    ]
